### ISSUE TITLE
On iOS7 it doesn't rotate

### ISSUE THREAD

**Issue by DrAma999** [nhdang103/HDNotificationView#1]
Prior iOS8 UIScreen instances doesn't rotate, that means that in iOS7 your HDNotificationViews in landscape they appear only at the upper top corner as they were in Portrait. To handle that you need to apply transformations according to device rotation changes.
From apple doc of UIScreen:
_Prior to iOS 8, a screen’s bounds rectangle always reflected the screen dimensions relative to a portrait-up orientation. Rotating the device to a landscape or upside-down orientation did not change the bounds. In iOS 8 and later, a screen’s bounds property takes the interface orientation of the screen into account. This behavior means that the bounds for a device in a portrait orientation may not be the same as the bounds for the device in a landscape orientation. Apps that rely on the screen dimensions can use the object in the fixedCoordinateSpace property as a fixed point of reference for any calculations they must make._

**Comment by nhdang103** [comment]
Thanks for your feedback, i will update it asap.
