### ISSUE TITLE
UIDeviceOrientationDidChangeNotification issue

### ISSUE THREAD

**Issue by hiddenparts** [nhdang103/HDNotificationView#12]
First, sorry to my poor English.

I found unintented bug by UIDeviceOrientationDidChangeNotification.

Code is received message by iOS at App state switching Foreground & Background.

so, code calls [self setUI] and creates Tap gesture and adds view overlap. 

finally, when view has tap gesture, view calls onTouch function repeatedly.

**Comment by nhdang103** [comment]
Thanks for your support. I'll update it asap

**Comment by ducnmisbk** [comment]
@hiddenparts : create property to pan gesture and tap gesture. Just check to create gesture on the first time call setupUI.
