### ISSUE TITLE
problem with MZFormSheetController

### ISSUE THREAD

**Issue by golfiti** [nhdang103/HDNotificationView#7]
My app use libs MZFormSheetController(https://github.com/m1entus/MZFormSheetController)

when notification appear after MZFormSheetController opened

MZFormSheetController will hide after HDNotificationView has show 
and when HDNotificationView hide MZFormSheetController will show again

**Comment by nhdang103** [comment]
Both two libraries are using key window as superview ==> You should make some configs. Thanks for your feedback
